version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/snapshot
hooks:
  BeforeInstall:
    - location: scripts/cleanup.sh
      timeout: 300
  AfterInstall:
    - location: scripts/dependencies.sh
      timeout: 300
      runas: root
    - location: scripts/pull_env_from_s3.sh
      timeout: 300
    - location: scripts/migrate.sh
      timeout: 300
    - location: scripts/optimize.sh
      timeout: 300

  ApplicationStart:
    - location: scripts/exit_maintenance_mode.sh
      timeout: 300
      runas: root

  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 300
